services:
  mongodb:
    image: mongo
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$ME_CONFIG_MONGODB_ADMINUSERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$ME_CONFIG_MONGODB_ADMINPASSWORD
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 27017:$DB_PORT
  app:
    build: .
    image: node:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_NAME
      - DB_PORT=$DB_PORT
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL=$ME_CONFIG_MONGODB_URL
    stdin_open: true
    tty: true
    command: npm run dev
    depends_on:
      - mongodb
    volumes:
      - ./:/app/
networks:
  backend:
    driver: bridge
     